feat: se implementa validacion por franquicia para envió de notificac…
epayco/Plugin_ePayco_WooCommerce pull request #31
Opened 2021-12-28 12:57 UTC by RicardoSaldarriagaPayco

…ion por correo

2021-12-29 16:55 UTC, JuanFelMesa requested changes

2021-12-29 16:55 UTC, JuanFelMesa commented on woocommerce-gateway-payco.php
> +                            }
@RicardoSaldarriagaPayco por que solo cuando es diferente a PSE ?

2021-12-29 17:09 UTC, RicardoSaldarriagaPayco commented on woocommerce-gateway-payco.php
> +                            }
@JuanFelMesa ya que Woocommerce solo permite enviar la notificación del pedido completado por correo cuando el pedido cambia de "pendiente de pago" a "completado", una vez la transacción es aceptada en epayco, para el caso con transacciones en PSE se envia una confirmación al comercio con estado pendiente mientras el banco aprueba la transaccion y el estado interno en Woocommerce se actualiza a  "ePayco Pago Pendiente", luego al procesarce la transaccion se actualiza el estado en Woocommerce a "completado" y no se envia el correo de notificacion al comercio ya que el estado anterior del pedido es diferente a "pendiente de pago", por lo tanto se implemento esta validación  para que cuando se envia la confirmación de pago con estado pendiente no se actualice el estado en Woocommerce como "ePayco Pago Pendiente" sino que deja el de Woocommerce por defecto "pendiente de pago" para que una vez se confirme el pago como aceptado en epayco, se actualice a "completado" el estado en Woocommerce y pueda enviar la notificación que el comercio requiere enviar a sus clientes, solo seria para los pagos con PSE, para los demas se esta enviando la notificación de forma correcta

2021-12-30 17:41 UTC, JuanFelMesa approved these changes

2021-12-30 17:41 UTC, merged

2021-12-30 17:41 UTC, JuanFelMesa commented
@RicardoSaldarriagaPayco  recuerda que debe ser releases, no feature